### ISSUE TITLE
Links in Schema

### ISSUE THREAD

**Issue by neomerx** [neomerx/json-api#119]
It would be nice to have an ability to create `related` relationship links from `Schema`. It could be used for pagination in relationships. Also the code could be reused from `Encoder` which has similar methods `withRelationshipRelatedLink` and `withRelationshipSelfLink`.

**Comment by lindyhopchris** [comment]
@neomerx 

Don't know if this is related, but there is a need to be able to reconstruct links from the parameters that were received from the client.

As an example, for pagination the links returned in the document level for pagination may need to include the filtering parameters because the client might be paging over filtered resources.

I've got a `feature/pagination` branch on my `laravel-json-api` package and I'm having to do this at the moment:

https://github.com/cloudcreativity/laravel-json-api/blob/feature/pagination/src/Schema/PaginationLink.php

Don't know what you think about adding to your package the ability to reconstruct links?

**Comment by neomerx** [comment]
@lindyhopchris that's [my solution](https://github.com/neomerx/limoncello/blob/develop/src/JsonApi/NumberAndSizePagingStrategy.php#L209-L230) for links reconstruction. Currently it works with `main` data and I'd like to reuse it for data in relationships too. This feature is a part of solution.

Btw have a look at new [limoncello-shot](https://github.com/neomerx/limoncello-shot/tree/lumen#installation)

**Comment by neomerx** [comment]
I've spotted and fixed lib design issue while working on this. In Schema relationship it was possible to set links which would appear in json api document (example below)

``` json
{
    "data" : {
        "type"  : "posts",
        "id"    : "1",
        "attributes" : {
            "title" : "...",
            "body"  : "..."
        },
        "relationships" : {
            "comments" : {
                "links" : { "boo" : "http://example.com/posts/1/another/link" }
            }
        }
    }
}
```

The problem was that `/posts/1/` part was fixed. The lib added it to all links with `$treatAsHref = false`. So a) it was inflexible b) link URLs were not truly URLs but only a part of it (without `/posts/1/`)

I got rid of it. However for some cases (I believe it's rarely used) it will cause incompatibility. Solution is simple. Instead of 

``` php
'boo' => new Link('another/link'),
```

link should be defined in `Schema` as

``` php
'boo' => new Link($this->getSelfSubUrl($post) . '/another/link'),
```
