### ISSUE TITLE
SchemaProvider::getRelationships default behaviour

### ISSUE THREAD

**Issue by lunika** [neomerx/json-api#167]
Hi,

I don't really understand the default behaviour for the method `Neomerx\JsonApi\Schema\SchemaProvider::getRelationships`, this line exactly : https://github.com/neomerx/json-api/blob/master/src/Schema/SchemaProvider.php#L201

is there some magic I don't understand ?

Thanks

**Comment by neomerx** [comment]
Suppress 'unused variable' warning. The code will be removed by optimizer.

**Comment by lunika** [comment]
Thanks for your answer but suppress to don't have warning in what ? php code_sniffer ?

**Comment by neomerx** [comment]
I'm using PhpStorm which annoys me with warnings on this. Great IDE though.
IMHO from PHP 7 it's better to use `assert(...)`.

**Comment by Taluu** [comment]
... did you know you can suppress these things ? Making things _because_ of a tool (PHPStorm, Scrutinizer, unit tests, ...) is kind of a sign of bad design...

P.S : `assert` is not for that (it's to assert a value actually, triggering an exception if it's not valid)

**Comment by lunika** [comment]
well IMHO you should do nothing, this is not because your IDE blink a little bit that you should implement dead and useless code. And I don't understand why you would like to use `assert`, there is nothing to check here.

**Comment by neomerx** [comment]
Thanks all for your positive comments. Feel free to override the method the way you like.

**Comment by neomerx** [comment]
@lunika For the reason that from PHP 7 the framework guarantees you that any code in assert will be removed when run in production mode. Before PHP 7 I had to rely on how optimizer works among 5.5, 5.6 and HHVM. I considered a few options and found that one meeting the needs.

**Comment by neomerx** [comment]
@Taluu Have a screenshot of you comment and put it to your calendar to review in 5 years. I bet you will see your 'design mantra' differently. Just a pro advice.

**Comment by Taluu** [comment]
@neomerx For the assert, reading the docs (and the rfc, etc), the default is that a warning will be generated (because the default is *not* "ignore in prod" -- yes, you SHOULD configure properly, but note that it is not a MUST).

BTW, my "design mantra" as you call it is evolving. Whenever I find something that displease me while it was looking good even a month back, I'm trying NOT to continue in the wrong path. I'm not "oh well my opinion will change". Especially when someone points me something is wrong. This is my "pro advice".

But... whatever. Your project, your ideals.
