### ISSUE TITLE
InvalidArgumentException thrown when parsing an specific Accept header

### ISSUE THREAD

**Issue by Ilyes512** [neomerx/json-api#193]
The AcceptHeader cannot successfully parse the below `Accept` header and throws an InvalidArgumentException with the message `mediaType`:

```
application/vnd.api+json;q=0.5,text/html;q=0.8;*/*;q=0.1
```

I think its because of the second part: `text/html;q=0.8;*/*;q=0.1`. It tries to find the equal sign (`=`) in `*/*`: 
https://github.com/neomerx/json-api/blob/master/src/Http/Headers/AcceptMediaType.php#L134-L136

I believe the above accept header content is valid.

**Comment by neomerx** [comment]
Sorry for the delay in reply. I'm the first day back from vacation.

In order to decide how the parser should behave it is required to understand whether such value is a valid `Accept` header. The [RFC](https://tools.ietf.org/html/rfc2616#section-14.1) says that `*/*;q=0.1` falls into `accept-extension` part which has the following syntax

>        accept-extension = ";" token [ "=" ( token | quoted-string ) ]

As far as I understand it `=` is mandatory so the input value is invalid. How do you think?

**Comment by neomerx** [comment]
I think you mistyped `;` instead of `,` and really meant `application/vnd.api+json;q=0.5,text/html;q=0.8,*/*;q=0.1`

The string above will work fine and return 3 media types parsed.

**Comment by Ilyes512** [comment]
Ah, yes I see. You are correct :). I will try it out next day and also try some other combinations. I will close this issue when I have done so (or close it it now if you like). Thanks for looking at this!

**Comment by neomerx** [comment]
Feel free to report any found issues, I'm ok to reopen.
