### ISSUE TITLE
Allow override of isPathRequested() in Parser implementation

### ISSUE THREAD

**Issue by 66mm** [neomerx/json-api#231]
It would be great if the visibility of `Parser::isPathRequested()` can be changed from `private` to `protected` so it can be easily overridden.

The reason for this request is i implemented support for wildcard include paths and check them in the mentioned method. For now i have to copy your complete parser implementation to achieve this.

**Comment by neomerx** [comment]
Hi, I've created a branch `issue231` with better `Parser` extensibility. Can you please modify custom parser and test in a suite [created for your case](https://github.com/neomerx/json-api/tree/issue231/tests/Extensions/Issue231)?

NB Travis fails because `Extensions/Issue231/IssueTest.php:90` is longer than 120 chars.

**Comment by neomerx** [comment]
Updated. @66mm Please have a look.

**Comment by neomerx** [comment]
@66mm Ping

**Comment by 66mm** [comment]
Sorry, was busy over the Weekend. 
Looks fine for me. Would be great if it will be merged into master. Thank you!

**Comment by neomerx** [comment]
pushed to `develop`. Will be pushed to `master` and released in a couple of days.

**Comment by neomerx** [comment]
Published https://github.com/neomerx/json-api/releases/tag/v3.0.3
Thanks for the support :star2:
